### ISSUE TITLE
"Pathfinding"

### ISSUE THREAD

**Issue by Foxboron** [Foxboron/Regius#1]
Så vi trenger en måte å finne path på. Vi vet lengden på kartet og vår posisjon, så vi kan
regne oss frem til hvor vi er, og neste tile vi skal til.
Der etter kan vi bare parse ut tile i rekke følge som vi spørr etter dem.

"left" "up" "down" "turn-right" "turn-left" osvosv

Samle tråd for diskusjon om dette :D

**Comment by Foxboron** [comment]
Init med kart

``` python
{u'map': {u'tile_height': 128, u'tiles': [[u'.', u'.', u'.', u'.', u'.', u'.', u'.', u'.'], [u'.', u'/', u'-', u'-', u'-', u'`', u'.', u'.'], [u'.', u'|', u'.', u'.', u'.', u'|', u'.', u'.'], [u'.', u'|', u'.', u'.', u'.', u'|', u'.', u'.'], [u'.', u'\\', u'-', u'-', u'-', u',', u'.', u'.'], [u'.', u'.', u'.', u'.', u'.', u'.', u'.', u'.']], u'tile_width': 128, u'path': [{u'tile_y': 1, u'tile_x': 3}, {u'tile_y': 1, u'tile_x': 4}, {u'tile_y': 1, u'tile_x': 5}, {u'tile_y': 2, u'tile_x': 5}, {u'tile_y': 3, u'tile_x': 5}, {u'tile_y': 4, u'tile_x': 5}, {u'tile_y': 4, u'tile_x': 4}, {u'tile_y': 4, u'tile_x': 3}, {u'tile_y': 4, u'tile_x': 2}, {u'tile_y': 4, u'tile_x': 1}, {u'tile_y': 3, u'tile_x': 1}, {u'tile_y': 2, u'tile_x': 1}, {u'tile_y': 1, u'tile_x': 1}, {u'tile_y': 1, u'tile_x': 2}], u'modifiers': [{u'y': 218, u'x': 168, u'height': 64, u'type': u'mud', u'width': 64}, {u'y': 538, u'x': 418, u'height': 32, u'type': u'booster', u'width': 32}, {u'y': 188, u'x': 638, u'height': 64, u'type': u'ice', u'width': 64}]}, u'id': 0}
```

Respons vi får fra server

``` python
{u'cars': [{u'direction': {u'y': 0, u'x': 1}, u'drift': 0, u'pos': {u'y': 153, u'x': 448.138885}, u'height': 43, u'width': 33, u'velocity': {u'y': -1.639177e-07, u'x': 4.166667}, u'id': 0}], u'boxes': [{u'y': 153, u'x': 576, u'height': 16, u'width': 16}, {u'y': 174, u'x': 576, u'height': 16, u'width': 16}, {u'y': 195, u'x': 576, u'height': 16, u'width': 16}, {u'y': 216, u'x': 576, u'height': 16, u'width': 16}, {u'y': 537, u'x': 448, u'height': 16, u'width': 16}, {u'y': 558, u'x': 448, u'height': 16, u'width': 16}, {u'y': 579, u'x': 448, u'height': 16, u'width': 16}, {u'y': 600, u'x': 448, u'height': 16, u'width': 16}], u'shells': []}
```

**Comment by krazyglitch** [comment]
Hvis vi satser på at det å drifte får oss raskere rundt banen skal det være mulig å lage en formel, eller tilnærminger på hvor vi kommer til å ende opp om x frames/sekunder. Da skal det kunne gå greit å ta en risikosjekk på forskjellige paths og speeds.

**Comment by Foxboron** [comment]
Noe i den banen jeg tenkte.
I første omgang prøver vi å få til noe som hvertfall kjører rundt banen.
Tenker vi bare ser fremover 2-3 "moves" for hver iterasjon. Så har vi padding med fart. Så om vi er i gir 1, så gir vi ut 2-3 ups pr iterasjon. Så kan bilen vite "k, sving så legger vi "ned" et gir" og da gir ut mindre fart.

Thoughts?

**Comment by krazyglitch** [comment]
Er det nå satt opp slik at vi vet farten? Ev. regne ut hvor fort vi beveger oss i tiles og tweake ut fra det. Kanskje se hvor skarp svingen er.

**Comment by Foxboron** [comment]
`u'velocity': {u'y': -1.639177e-07, u'x': 4.166667}`
Vi vet velocity til enhver tid.

**Comment by krazyglitch** [comment]
~~Da starter vi vel med å finne ut hvilken rotasjon vi har?~~

EDIT: Ser nå at vi får direction. Da er det bare å transformere slik at vi får riktig view på krefter.

**Comment by krazyglitch** [comment]
Hvis jeg ikke tar helt feil er vi nødt til å kompensere for at vi kun har thrust bak, og ikke på sidene.

**Comment by Foxboron** [comment]
mmmmm, jeg vet faktisk ikke. Ikke mitt felt :P Tror vi fokuserer på at den klarer å kjøre en runde, så tar vi det der ifra.

Vi trenger noe som parser kartet, og vet hvilken retning vi skal kjøre.

**Comment by krazyglitch** [comment]
Parsing av kartet bør ikke være spesielt vanskelig. Retningen kan vi muligens finne ved å se fremover en bestemt avstand (kanskje bestemt av gir), se i begge retninger normalt på kollisjonspunkt og se hvor det er åpent?

**Comment by krazyglitch** [comment]
Kom nettopp på en ting som jeg bare skriver for å ikke glemme. Hvis vi regner ut en plausibel kurve vi kan kjøre langs instruerer vi karten til å sikte mot et punkt på kurven som er en viss lengde unna bestemt med gir som faktor.

**Comment by krazyglitch** [comment]
Nå er jeg helt elendig til å tegne, men her er noe av konseptet jeg tenkte på.
![pathing](https://cloud.githubusercontent.com/assets/6589457/6186615/f16798c6-b37b-11e4-9281-c9f7e718075c.png)

Rød linje er en kalkulert kurve.
Grønn linje ser rett fremover og går normalt når den treffer noe for å sjekke hvor det er åpent.
Karten retter seg inn mot et punkt ute på den røde kurven.

**Comment by Foxboron** [comment]
Jeg har tenkt tanken på dette. Det er slik f.eks Google Car (som er selvkjørende) faktisk gjør det. Problemet er at jeg har null peiling på hvordan dette kan implementeres :D 

Men igjen, spennende å prøve seg på det!
